name: scientist
version: 0.0.0.0

dependencies:
  - base > 4 && < 5

ghc-options:
  - -Weverything
  - -Wno-missing-exported-signatures # re-enables missing-signatures
  - -Wno-missing-import-lists
  - -Wno-missing-local-signatures
  - -Wno-missing-safe-haskell-mode
  - -Wno-monomorphism-restriction
  - -Wno-prepositive-qualified-module
  - -Wno-safe
  - -Wno-unsafe

default-extensions:
  - NoImplicitPrelude

library:
  source-dirs: library
  dependencies:
    - MonadRandom
    - random-shuffle
    - text
    - time
    - unliftio
    - unliftio-core

tests:
  spec:
    main: Spec.hs
    source-dirs: tests
    dependencies:
      - hspec
      - scientist
      - time
      - unliftio
