name: scientist
version: 0.0.0.0
maintainer: Freckle Education
category: Utils
github: freckle/scientist-hs
synopsis: A Haskell library for carefully refactoring critical paths.
description: Please see README.md

extra-doc-files:
  - README.md
  - CHANGELOG.md

dependencies:
  - base > 4 && < 5

ghc-options:
  - -Weverything
  - -Wno-missing-exported-signatures # re-enables missing-signatures
  - -Wno-missing-import-lists
  - -Wno-missing-local-signatures
  - -Wno-monomorphism-restriction
  - -Wno-unsafe
  - -Wno-safe

when:
  - condition: "impl(ghc >= 8.10)"
    ghc-options:
      - -Wno-missing-safe-haskell-mode
      - -Wno-prepositive-qualified-module

default-extensions:
  - NoImplicitPrelude

library:
  source-dirs: library
  dependencies:
    - MonadRandom
    - random-shuffle
    - text
    - unliftio
    - unliftio-core

tests:
  spec:
    main: Spec.hs
    source-dirs: tests
    dependencies:
      - hspec
      - scientist
      - unliftio

  readme:
    main: README.lhs
    ghc-options: -pgmL markdown-unlit
    dependencies:
      - markdown-unlit
      - scientist
      - text
      - unliftio
      - unliftio-core
